name = "paste-orcax"
main = "src/index.ts"
compatibility_date = "2026-01-11"

routes = [
  { pattern = "paste.orcax.net/*", zone_name = "orcax.net" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2"
bucket_name = "paste-orcax"
preview_bucket_name = "paste-orcax"

[vars]
MAX_UPLOAD_BYTES = "10485760"
DEFAULT_EXPIRES_SECONDS = "86400"
MAX_EXPIRES_SECONDS = "2592000"
TURNSTILE_SITE_KEY = "0x4AAAAAACL0-BvK4QTOWV6H"

[triggers]
crons = ["0 */6 * * *"]
